# colors

colors:
  base:
    white: "#ffffff"
    black: "#0b0b0b"
  baseAdjustSteps: 10
  schemes:
    default:
      brand:       "#ffe600"
      accent:      "#00e44e"
      success:     "hsl(136, 79%, 45%)"
      warning:     "#dae21e"
      danger:      "#e80f0f"
      info:        "#0080ff"
      interactive: "#178ee5"
    alternative:
      brand:       "#0089ff"
      success:     "#4fc970"
      warning:     "#b1b907"
      danger:      "#ea3838"
      info:        "#237cd4"
  schemesAdjustSteps: 5
  metaThemeColor: "#dee600"
  colorGuides: "#ff0080"
  
  
#grid

grid:
  breakpoints:
    xs: 0
    sm: 576
    md: 768
    lg: 992
    xl: 1200
  breakpointsUnit: px
  layoutMinWidth: 320px
  columns: 16
  gutters:
    wrapper: "(xs: 0, sm: 0, lg: 0)"
    container: "(xs: 16px, sm: 24px, lg: 64px)"
    row: false
    col: "(xs: 8px, md: 16px)"
  fixWrapperWidth: false
  rotateBackMap: false
  
  
#spacers  
  
spacers:
  spacer: 8px
  spacerMap:
    a: "(xs: 2, sm: 3, lg: 0)"
    b: "(lg: 8)"
    c: "(xs: 4)"
    d: "(xs: 6)"
    e: "(xs: 10)"
  defaultMarginY:
    container: false
    row: false
    col: false
  defaultColPadding: false
  
  
#typography  
  
typography:
  fontsInclude:
    "Consolas": 400
    "Consolas-Bold": 700
  fontMain:       "Consolas"
  fontStyle:      "sans-serif"
  htmlFontSize:   12px
  fontSizeBase:   1rem
  lineHeightBase: 1.5
  fontWeightBase: normal